language: node_js
before_install:
- nvm install stable
- node -v
- npm -v
- npm install -g gulp
- npm install gulp
- npm install gulp-typescript
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: Fu6yNi5XkunLchMMJyOA0cWZItHRKwCh6rrVOesv7HpnsPvWwSjqoJquUogTJZ30vxgOz8waSX7udvBfgNdm8IAXuutGUBWtv26kuW0mzVv80RfDf9tXx8QumuKn6jnsRvCwPoKIfbN8NgB7yKwBDA+oAltSbZODoi25Tf5XBwd8TYWR1iZIOxfNo5q5FD4UPFdAss7zvcAl1PDoxRb/Hq0Nb7GOaMoAXG9vRIGYySv/OHxdbBQA7HlkJPhGmZ67+8f55+YIghkYKhqd0URT7nYUWh8X8KqriNR/8NDMbUd4unY8y98eqp6tbbjiWr89nISYcdWr6B94mHGyiSgI63Met1FIx+hP6e/aqFwsH42ULtaxCgAReKfsZMN05KTdQvEivcQofCkZfjKw5HPIo7mZKHfReZcxR1uqoL/yqeJuEEYrgKLTTOfwey4A9HnX5u+jrG+RBKq3238TqdzRu840531F+c9OvV28DXKt0A2iBaOlMvH4GgzlB2l+W0yL1jpuzGQcwBunLhLIMyqtObyjIW0BBYf6ElVGysGhbCVS3/S4xmUoZ63p2xpny3HLyzKjES7hVRIocn7g4awcWAk0n7wy/IS7ykw3bf26sptpCPAxaOTnwcyfT7WIjsHBzJ1CyiJLAzu+wfu8mj3FenhG9sVXGjQQI5BYU9mFATI=
  on:
    tags: true
    repo: pushrocks/gulp-jsonjade
notifications:
  slack:
    secure: IyS9S/rmR25k3z1tgXIkHz48X4zpW+4R8WY8VKq3LxwRsZ2nhsfJyl8f97NpC8zKSVwtPMVb2v3cskLMfqZfPA1p8N+z4e7v/pSlAfyVQBNkyuvSZC/Hg30h0GfrGij3qpcEf6VrvdngY7MdtfmlSX61rdhYJIB6Sw3XIZg4RFE/T8G/E9mipzcdRbHYjSdVe27kmAF6dOZI/mMCtMUylHYHh5ICywEWFbS0FVogvFRL0n8LgFlV5axFo1tdfX0YtNm6e6aCTLtMYPBUVSPUGm+nPRmZqzA/bpqgXcG80zO7zaj0Uc7tsezKLZYilK9nMV1pgGpq4v4vn6E5ULWX1BXi/T7HCDZdoh12BytbFALXkNRx1i8pBXWDOoYUTuoNgFVUoFBSsAIwCNTOExCWXsPvlTYypNYaNEIJ66GGmjyW+I0egI5IJ5craA0L9prnSzCnTSh7SmAV0/PEXJ5YQqIjyNUX6kvZl6Ti2KlXd/c+znKG1YxO19WitH5wqsmlTJSDvw7BRS4ObdEcWlHoqSfBBgfoWdnYUJ+Q8lkoupo0fnxnC9UmHRuQlHQLRq39vAc8ty4uGYuvwQ+qz6CG+3fZ1xNXSL0Gtb7D0PNP5pLXJykqxaWHeErxRS1oCGiagqhXBw20Yrav1/sZ3xO1u+g9/TfcsLKNAl5bAzMHznE=
